name: binary_counter
description: A library for performing binary operations.
version: 0.0.3+2
# homepage: https://www.example.com
repository: https://github.com/LiveUser/binary_counter

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  number_system: ^0.0.5+7